# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 737)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drive = QtWidgets.QGroupBox(self.centralwidget)
        self.drive.setObjectName("drive")
        self.gridLayout = QtWidgets.QGridLayout(self.drive)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.drive)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.drive)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.drive)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.drive)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.drive_active = QtWidgets.QLabel(self.drive)
        self.drive_active.setEnabled(True)
        self.drive_active.setFrameShape(QtWidgets.QFrame.Box)
        self.drive_active.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drive_active.setObjectName("drive_active")
        self.gridLayout.addWidget(self.drive_active, 6, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(self.drive)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.drive_model = QtWidgets.QComboBox(self.drive)
        self.drive_model.setObjectName("drive_model")
        self.gridLayout.addWidget(self.drive_model, 0, 1, 1, 3)
        self.drive_addr = QtWidgets.QSpinBox(self.drive)
        self.drive_addr.setMaximum(7)
        self.drive_addr.setObjectName("drive_addr")
        self.gridLayout.addWidget(self.drive_addr, 2, 1, 1, 1)
        self.drive_protocol = QtWidgets.QLabel(self.drive)
        self.drive_protocol.setObjectName("drive_protocol")
        self.gridLayout.addWidget(self.drive_protocol, 3, 1, 1, 1)
        self.drive_capacity = QtWidgets.QLabel(self.drive)
        self.drive_capacity.setObjectName("drive_capacity")
        self.gridLayout.addWidget(self.drive_capacity, 4, 1, 1, 1)
        self.drive_geometry = QtWidgets.QLabel(self.drive)
        self.drive_geometry.setObjectName("drive_geometry")
        self.gridLayout.addWidget(self.drive_geometry, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.drive)
        self.unit0 = QtWidgets.QGroupBox(self.centralwidget)
        self.unit0.setObjectName("unit0")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.unit0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.unit0)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.unit0_file = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit0_file.sizePolicy().hasHeightForWidth())
        self.unit0_file.setSizePolicy(sizePolicy)
        self.unit0_file.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_file.setText("")
        self.unit0_file.setObjectName("unit0_file")
        self.gridLayout_2.addWidget(self.unit0_file, 0, 1, 1, 1)
        self.unit0_load = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit0_load.sizePolicy().hasHeightForWidth())
        self.unit0_load.setSizePolicy(sizePolicy)
        self.unit0_load.setObjectName("unit0_load")
        self.gridLayout_2.addWidget(self.unit0_load, 0, 2, 1, 1)
        self.unit0_readonly = QtWidgets.QCheckBox(self.groupBox_3)
        self.unit0_readonly.setObjectName("unit0_readonly")
        self.gridLayout_2.addWidget(self.unit0_readonly, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.unit0)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.unit0_lba = QtWidgets.QLabel(self.groupBox_4)
        self.unit0_lba.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_lba.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit0_lba.setObjectName("unit0_lba")
        self.gridLayout_3.addWidget(self.unit0_lba, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 2, 1, 1)
        self.unit0_cyl = QtWidgets.QLabel(self.groupBox_4)
        self.unit0_cyl.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_cyl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit0_cyl.setObjectName("unit0_cyl")
        self.gridLayout_3.addWidget(self.unit0_cyl, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 4, 1, 1)
        self.unit0_head = QtWidgets.QLabel(self.groupBox_4)
        self.unit0_head.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_head.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit0_head.setObjectName("unit0_head")
        self.gridLayout_3.addWidget(self.unit0_head, 1, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 6, 1, 1)
        self.unit0_sec = QtWidgets.QLabel(self.groupBox_4)
        self.unit0_sec.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_sec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit0_sec.setObjectName("unit0_sec")
        self.gridLayout_3.addWidget(self.unit0_sec, 1, 7, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 2, 1, 1)
        self.unit0_read = QtWidgets.QLabel(self.groupBox_4)
        self.unit0_read.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_read.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit0_read.setObjectName("unit0_read")
        self.gridLayout_3.addWidget(self.unit0_read, 0, 1, 1, 1)
        self.unit0_write = QtWidgets.QLabel(self.groupBox_4)
        self.unit0_write.setFrameShape(QtWidgets.QFrame.Box)
        self.unit0_write.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit0_write.setObjectName("unit0_write")
        self.gridLayout_3.addWidget(self.unit0_write, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.unit0)
        self.unit1 = QtWidgets.QGroupBox(self.centralwidget)
        self.unit1.setEnabled(True)
        self.unit1.setObjectName("unit1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.unit1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.unit1)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.unit1_file = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit1_file.sizePolicy().hasHeightForWidth())
        self.unit1_file.setSizePolicy(sizePolicy)
        self.unit1_file.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_file.setText("")
        self.unit1_file.setObjectName("unit1_file")
        self.gridLayout_4.addWidget(self.unit1_file, 0, 1, 1, 1)
        self.unit1_load = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit1_load.sizePolicy().hasHeightForWidth())
        self.unit1_load.setSizePolicy(sizePolicy)
        self.unit1_load.setObjectName("unit1_load")
        self.gridLayout_4.addWidget(self.unit1_load, 0, 2, 1, 1)
        self.unit1_readonly = QtWidgets.QCheckBox(self.groupBox_6)
        self.unit1_readonly.setObjectName("unit1_readonly")
        self.gridLayout_4.addWidget(self.unit1_readonly, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.unit1)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 1, 0, 1, 1)
        self.unit1_lba = QtWidgets.QLabel(self.groupBox_7)
        self.unit1_lba.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_lba.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit1_lba.setObjectName("unit1_lba")
        self.gridLayout_5.addWidget(self.unit1_lba, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 1, 2, 1, 1)
        self.unit1_cyl = QtWidgets.QLabel(self.groupBox_7)
        self.unit1_cyl.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_cyl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit1_cyl.setObjectName("unit1_cyl")
        self.gridLayout_5.addWidget(self.unit1_cyl, 1, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 1, 4, 1, 1)
        self.unit1_head = QtWidgets.QLabel(self.groupBox_7)
        self.unit1_head.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_head.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit1_head.setObjectName("unit1_head")
        self.gridLayout_5.addWidget(self.unit1_head, 1, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 1, 6, 1, 1)
        self.unit1_sec = QtWidgets.QLabel(self.groupBox_7)
        self.unit1_sec.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_sec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit1_sec.setObjectName("unit1_sec")
        self.gridLayout_5.addWidget(self.unit1_sec, 1, 7, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_7)
        self.label_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 0, 2, 1, 1)
        self.unit1_read = QtWidgets.QLabel(self.groupBox_7)
        self.unit1_read.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_read.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit1_read.setObjectName("unit1_read")
        self.gridLayout_5.addWidget(self.unit1_read, 0, 1, 1, 1)
        self.unit1_write = QtWidgets.QLabel(self.groupBox_7)
        self.unit1_write.setFrameShape(QtWidgets.QFrame.Box)
        self.unit1_write.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit1_write.setObjectName("unit1_write")
        self.gridLayout_5.addWidget(self.unit1_write, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.verticalLayout.addWidget(self.unit1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.drive_addr.valueChanged['int'].connect(MainWindow.set_address)
        self.drive_model.currentIndexChanged['int'].connect(MainWindow.set_model)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.drive_model, self.drive_addr)
        MainWindow.setTabOrder(self.drive_addr, self.unit0_load)
        MainWindow.setTabOrder(self.unit0_load, self.unit0_readonly)
        MainWindow.setTabOrder(self.unit0_readonly, self.unit1_load)
        MainWindow.setTabOrder(self.unit1_load, self.unit1_readonly)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HP disk simulator v1.0"))
        self.drive.setTitle(_translate("MainWindow", "Drive"))
        self.label_3.setText(_translate("MainWindow", "Protocol"))
        self.label_4.setText(_translate("MainWindow", "Capacity"))
        self.label.setText(_translate("MainWindow", "Model"))
        self.label_2.setText(_translate("MainWindow", "Address"))
        self.drive_active.setText(_translate("MainWindow", "Active"))
        self.label_6.setText(_translate("MainWindow", "Geometry"))
        self.drive_protocol.setText(_translate("MainWindow", "XXX"))
        self.drive_capacity.setText(_translate("MainWindow", "XXX"))
        self.drive_geometry.setText(_translate("MainWindow", "XXXxXXxXX"))
        self.unit0.setTitle(_translate("MainWindow", "Unit 0"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Image"))
        self.label_10.setText(_translate("MainWindow", "File"))
        self.unit0_load.setText(_translate("MainWindow", "Load"))
        self.unit0_readonly.setText(_translate("MainWindow", "Read only"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Status"))
        self.label_21.setText(_translate("MainWindow", "Read"))
        self.label_14.setText(_translate("MainWindow", "Block"))
        self.unit0_lba.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Cylinder"))
        self.unit0_cyl.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "Head"))
        self.unit0_head.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "Sector"))
        self.unit0_sec.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "Write"))
        self.unit0_read.setText(_translate("MainWindow", "0"))
        self.unit0_write.setText(_translate("MainWindow", "0"))
        self.unit1.setTitle(_translate("MainWindow", "Unit 1"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Image"))
        self.label_22.setText(_translate("MainWindow", "File"))
        self.unit1_load.setText(_translate("MainWindow", "Load"))
        self.unit1_readonly.setText(_translate("MainWindow", "Read only"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Status"))
        self.label_24.setText(_translate("MainWindow", "Read"))
        self.label_26.setText(_translate("MainWindow", "Block"))
        self.unit1_lba.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "Cylinder"))
        self.unit1_cyl.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Head"))
        self.unit1_head.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "Sector"))
        self.unit1_sec.setText(_translate("MainWindow", "0"))
        self.label_33.setText(_translate("MainWindow", "Write"))
        self.unit1_read.setText(_translate("MainWindow", "0"))
        self.unit1_write.setText(_translate("MainWindow", "0"))

